/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.creditcard;

import java.awt.Color;
import java.io.Serializable;
import org.apache.commons.validator.routines.CreditCardValidator;

/**
 *
 * @author Alumno Tarde
 */
public class CreditCard extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form CreditCard
     */
    public CreditCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero = new javax.swing.JTextField();
        numeroLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        mes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        anyo = new javax.swing.JTextField();
        ccvLabel = new javax.swing.JLabel();
        ccv = new javax.swing.JTextField();

        numero.setColumns(16);
        numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroFocusLost(evt);
            }
        });

        numeroLabel.setText("Numero:");

        fechaLabel.setText("Caducidad:");

        mes.setColumns(2);
        mes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mesFocusLost(evt);
            }
        });

        jLabel3.setText("/");

        anyo.setColumns(2);
        anyo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                anyoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                anyoFocusLost(evt);
            }
        });

        ccvLabel.setText("CCV:");

        ccv.setColumns(3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaLabel)
                    .addComponent(numeroLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ccvLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(anyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccvLabel)
                    .addComponent(ccv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroFocusGained
        numero.setForeground(Color.black);
    }//GEN-LAST:event_numeroFocusGained

    private void numeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroFocusLost
        CreditCardValidator cc = new CreditCardValidator();
        if(!cc.isValid(numero.getText())) {
            numero.setForeground(Color.red);
        }
    }//GEN-LAST:event_numeroFocusLost

    private void mesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesFocusGained
        mes.setForeground(Color.black);
    }//GEN-LAST:event_mesFocusGained

    private void mesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesFocusLost
        if (mes.getText().length() != 0) {
            int mesNum = Integer.parseInt(mes.getText());

            if(mesNum > 12 || mesNum <= 0) {
                mes.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_mesFocusLost

    private void anyoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anyoFocusGained
        anyo.setForeground(Color.black);
    }//GEN-LAST:event_anyoFocusGained

    private void anyoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anyoFocusLost
        if (anyo.getText().length() != 0) {
            int anoNum = Integer.parseInt(anyo.getText());
        
            if(anoNum < 20 ) {
                anyo.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_anyoFocusLost

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anyo;
    private javax.swing.JTextField ccv;
    private javax.swing.JLabel ccvLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField numero;
    private javax.swing.JLabel numeroLabel;
    // End of variables declaration//GEN-END:variables
}
